name: Package JSONL Files

on:
  push:
    paths:
      - "**.jsonl" # Run this workflow when JSONL files are pushed
  workflow_dispatch: # Run this workflow manually

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload JSONL files
        uses: actions/upload-artifact@v4
        with:
          name: jsonl-files
          path: '*.jsonl'
